"""Coherent, bounded corpus snapshots built from exact authoritative bytes."""
from __future__ import annotations

import contextlib
import hashlib
import json
import os
import re
import stat
import time
import unicodedata
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from datetime import date, datetime, timezone
from datetime import time as datetime_time
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any

import yaml
from bounded_io import read_stable_bytes
from code_languages import language_for_path
from page_status import is_retired
from vault_editorial import EDITORIAL_NAMES

COLLECTOR_VERSION = "corpus-collector/v1"
EXTRACTOR_VERSION = "markdown-heading-extractor/v2"

MAX_CORPUS_FILES = 10_000
MAX_CORPUS_FILE_BYTES = 8 * 1024 * 1024
MAX_CORPUS_TOTAL_BYTES = 64 * 1024 * 1024
MAX_CORPUS_INSPECTED_ENTRIES = 50_000
MAX_CORPUS_DIRECTORIES = 5_000
MAX_CORPUS_DEPTH = 16
MAX_CORPUS_HEADINGS = 100_000
MAX_CORPUS_CHUNKS = 100_000
DEFAULT_DEADLINE_SECONDS = 30.0

PROJECT_FILES = frozenset({"state.md", "journal.md", "context.md"})
SESSION_RECORD_ROOT = "knowledge/raw/sessions"
APPROVED_CODE_ROOTS = frozenset(
    {"benchmark", "docs", "integrations", "rules", "scripts", "skills", "tests"}
)
ARCHIVE_DIRECTORIES = frozenset({"archive", ".archive", "_archive"})
# `__pycache__` holds generated bytecode, never a source, and every vault
# that has run Python once has one under its code roots.
SKIP_DIRECTORIES = frozenset({"__pycache__", "_template", "gaps", "raw-sources"})
_HEADING = re.compile(
    rb"(?m)^[ \t]{0,3}(#{1,6})(?:[ \t]+([^\r\n]*?)|[ \t]*)(?:\r?\n|$)"
)
_FENCE = re.compile(rb"^[ ]{0,3}(`{3,}|~{3,})([^\r\n]*)$")
_CLOSING_HASHES = re.compile(r"[ \t]+#+[ \t]*$")
_CYRILLIC = re.compile(r"[\u0400-\u04ff]")
_HAN = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")
_LATIN = re.compile(r"[A-Za-z]")


_POLICY_BOUNDS = {
    "roots": (1, 128),
    "include_globs": (1, 256),
    "ignore_globs": (0, 256),
    "suffixes": (1, 128),
}


def _bounded_nfc_text(value: object, limit: int) -> bool:
    if not isinstance(value, str) or not value:
        return False
    return len(value) <= limit and value == unicodedata.normalize("NFC", value)


def _normalized_text(value: str, limit: int) -> bool:
    if not _bounded_nfc_text(value, limit):
        return False
    return "\\" not in value


def _relative_parts_ok(pure: PurePosixPath) -> bool:
    if pure.is_absolute():
        return False
    return not any(part in {"", ".", ".."} for part in pure.parts)


def _normalized_values(name: str, values: tuple[str, ...]) -> tuple[str, ...]:
    nfc_values = tuple(unicodedata.normalize("NFC", value) for value in values)
    if len(set(nfc_values)) < len(set(values)):
        raise ValueError(f"{name} contains a Unicode normalization collision")
    if name == "suffixes":
        return tuple(value.casefold() for value in nfc_values)
    return nfc_values


def _normalize_policy_tuples(policy: object) -> None:
    for name in _POLICY_BOUNDS:
        values = getattr(policy, name)
        if isinstance(values, tuple) and all(isinstance(value, str) for value in values):
            object.__setattr__(policy, name, _normalized_values(name, values))


def _all_nonempty_strings(values: tuple) -> bool:
    return all(isinstance(value, str) and value for value in values)


def _bounded_unique_tuple(values: object, minimum: int, maximum: int) -> bool:
    if not isinstance(values, tuple):
        return False
    if not minimum <= len(values) <= maximum:
        return False
    return values == tuple(sorted(set(values))) and _all_nonempty_strings(values)


def _require_policy_tuples(policy: object) -> None:
    for name, (minimum, maximum) in _POLICY_BOUNDS.items():
        if not _bounded_unique_tuple(getattr(policy, name), minimum, maximum):
            raise ValueError(f"{name} must be a bounded sorted unique tuple")


def _normalized_relative_root(root: str) -> bool:
    if not _normalized_text(root, 4096) or root == ".":
        return False
    return _relative_parts_ok(PurePosixPath(root))


def _require_policy_roots(roots: tuple[str, ...]) -> None:
    if any(not _normalized_relative_root(root) for root in roots):
        raise ValueError("roots must contain normalized relative POSIX paths")


def _windows_rooted(value: str) -> bool:
    windows_path = PureWindowsPath(value)
    return bool(windows_path.drive or windows_path.root)


def _dot_segments(value: str) -> bool:
    if value.startswith("./") or "//" in value:
        return True
    return any(part == "." for part in value.split("/"))


def _normalized_glob(value: str) -> bool:
    if not _normalized_text(value, 4096):
        return False
    if _windows_rooted(value) or _dot_segments(value):
        return False
    return _relative_parts_ok(PurePosixPath(value))


def _require_policy_globs(policy: object) -> None:
    for name in ("include_globs", "ignore_globs"):
        if any(not _normalized_glob(value) for value in getattr(policy, name)):
            raise ValueError(f"{name} must contain normalized relative POSIX globs")


def _normalized_suffix(value: str) -> bool:
    if not _normalized_text(value, 128):
        return False
    if value != value.casefold() or not value.startswith(".") or len(value) < 2:
        return False
    return "/" not in value


def _require_policy_suffixes(suffixes: tuple[str, ...]) -> None:
    if any(not _normalized_suffix(value) for value in suffixes):
        raise ValueError("suffixes must contain normalized lowercase suffixes")


def _encoded_source_id(source_id: object) -> bytes:
    try:
        return source_id.encode("utf-8")
    except (AttributeError, UnicodeEncodeError) as exc:
        raise ValueError("source_id must be valid UTF-8 text") from exc


def _require_source_id(source_id: object) -> None:
    encoded = _encoded_source_id(source_id)
    if not encoded or not _bounded_nfc_text(source_id, 512):
        raise ValueError("source_id must be normalized UTF-8 text of at most 512 characters")


_CODE_LIMIT_MAXIMA = {
    "max_files": 1_000_000,
    "max_file_bytes": 1024**3,
    "max_total_bytes": 16 * 1024**3,
    "max_entries": 5_000_000,
    "max_directories": 1_000_000,
    "max_depth": 256,
    "chunk_bytes": 8 * 1024 * 1024,
}
_CODE_LIMIT_MINIMA = {"max_depth": 1, "chunk_bytes": 4096}


def _whole_number(value: object) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def _require_limit_in_range(field: str, value: object, minimum: int, maximum: int) -> None:
    if _whole_number(value) and minimum <= value <= maximum:
        return
    raise ValueError(f"{field} must be an integer from {minimum} to {maximum}")


def _require_non_negative(name: str, value: object) -> None:
    if _whole_number(value) and value >= 0:
        return
    raise ValueError(f"{name} must be a non-negative integer")


def _plain_relative_text(value: object) -> str | None:
    """The path as text when it is bounded NFC without a backslash, else None."""
    if not _bounded_nfc_text(value, 4096):
        return None
    text = str(value)
    return None if "\\" in text else text


def _valid_relative_path(value: object, reject_dot: bool) -> bool:
    text = _plain_relative_text(value)
    if text is None:
        return False
    if reject_dot and text == ".":
        return False
    return _relative_parts_ok(PurePosixPath(text))


def _require_relative_path(value: object, *, reject_dot: bool = False) -> None:
    if not _valid_relative_path(value, reject_dot):
        raise ValueError("relative_path must be normalized relative POSIX text")


def _require_sha256(value: object, label: str) -> None:
    if not isinstance(value, str) or re.fullmatch(r"[0-9a-f]{64}", value) is None:
        raise ValueError(f"{label} must be lowercase SHA-256")


def _ordered_by_path(items: object, kind: type) -> bool:
    if not isinstance(items, tuple):
        return False
    if any(not isinstance(item, kind) for item in items):
        return False
    paths = tuple(item.relative_path for item in items)
    return paths == tuple(sorted(paths))


def _require_manifest_versions(collector_version: object, extractor_version: object) -> None:
    if not isinstance(collector_version, str) or not collector_version:
        raise ValueError("collector_version must be a non-empty string")
    if not isinstance(extractor_version, str) or not extractor_version:
        raise ValueError("extractor_version must be a non-empty string")


def _require_unique_manifest_entries(entries: list[dict[str, str]]) -> None:
    paths = [entry["relative_path"] for entry in entries]
    logical_ids = [entry["logical_id"] for entry in entries]
    if len(paths) != len(set(paths)) or len(logical_ids) != len(set(logical_ids)):
        raise ValueError("canonical source membership paths and logical IDs must be unique")


def _require_safe_entry(path: Path, info: os.stat_result, *, symlink: bool) -> None:
    reparse = bool(
        (getattr(info, "st_file_attributes", 0) or 0)
        & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    )
    if symlink or reparse:
        raise PermissionError(f"unsafe corpus path: {path}")


class CorpusChanged(RuntimeError):
    """Live corpus membership or content differs from a captured snapshot."""


@dataclass(frozen=True, slots=True)
class SourceMetadata:
    type: str
    project: str | None = None
    authority: str | None = None
    confidence: str | None = None
    status: str = "active"
    valid_from: str | None = None
    valid_to: str | None = None
    language: str | None = None

    @property
    def source_authority(self) -> str | None:
        return self.authority


@dataclass(frozen=True, slots=True)
class SourceRecord:
    logical_id: str
    relative_path: str
    sha256: str
    size: int
    media_type: str
    language: str | None
    git_oid: str | None


@dataclass(frozen=True, slots=True)
class CapturedSource:
    record: SourceRecord
    metadata: SourceMetadata
    content: bytes

    @property
    def captured_bytes(self) -> bytes:
        return self.content


@dataclass(frozen=True, slots=True)
class RetrievalChunk:
    id: str
    source_id: str
    source_path: str
    parent_page: str
    heading_ancestry: tuple[str, ...]
    byte_start: int
    byte_end: int
    line_start: int
    line_end: int
    text: str
    source_sha256: str
    span_sha256: str
    type: str
    project: str | None
    authority: str | None
    confidence: str | None
    status: str
    valid_from: str | None
    valid_to: str | None
    language: str | None

    @property
    def chunk_id(self) -> str:
        return self.id

    @property
    def source_hash(self) -> str:
        return self.source_sha256


@dataclass(frozen=True, slots=True)
class SnapshotPolicy:
    daily_paths: tuple[str, ...]
    code_roots: tuple[str, ...]
    include_historical: bool
    as_of: str | None
    max_files: int
    max_file_bytes: int
    max_total_bytes: int
    max_entries: int
    max_directories: int
    max_depth: int


@dataclass(frozen=True, slots=True)
class RepositoryCodeLimits:
    max_files: int = 10_000
    max_file_bytes: int = 8 * 1024 * 1024
    max_total_bytes: int = 512 * 1024 * 1024
    max_entries: int = 50_000
    max_directories: int = 5_000
    max_depth: int = 32
    chunk_bytes: int = 64 * 1024

    def __post_init__(self) -> None:
        for field, maximum in _CODE_LIMIT_MAXIMA.items():
            minimum = _CODE_LIMIT_MINIMA.get(field, 1)
            _require_limit_in_range(field, getattr(self, field), minimum, maximum)


@dataclass(frozen=True, slots=True)
class RepositoryCodePolicy:
    roots: tuple[str, ...]
    include_globs: tuple[str, ...]
    ignore_globs: tuple[str, ...]
    suffixes: tuple[str, ...]

    def __post_init__(self) -> None:
        _normalize_policy_tuples(self)
        _require_policy_tuples(self)
        _require_policy_roots(self.roots)
        _require_policy_globs(self)
        _require_policy_suffixes(self.suffixes)


@dataclass(frozen=True, slots=True)
class FileStatMetadata:
    size: int
    mtime_ns: int
    ctime_ns: int
    mode: int
    device: int
    inode: int

    def __post_init__(self) -> None:
        for name in self.__dataclass_fields__:
            _require_non_negative(name, getattr(self, name))


@dataclass(frozen=True, slots=True)
class CodeCaptureFile:
    source_id: str
    relative_path: str
    sha256: str
    stat: FileStatMetadata

    def __post_init__(self) -> None:
        _require_source_id(self.source_id)
        _require_relative_path(self.relative_path)
        _require_sha256(self.sha256, "sha256")
        if not isinstance(self.stat, FileStatMetadata):
            raise TypeError("stat must be FileStatMetadata")


@dataclass(frozen=True, slots=True)
class DirectoryMembership:
    relative_path: str
    entry_count: int
    entries_sha256: str

    def __post_init__(self) -> None:
        _require_relative_path(self.relative_path, reject_dot=True)
        if isinstance(self.entry_count, bool) or not isinstance(self.entry_count, int):
            raise ValueError("entry_count must be a non-negative integer")
        if self.entry_count < 0:
            raise ValueError("entry_count must be a non-negative integer")
        _require_sha256(self.entries_sha256, "entries_sha256")


@dataclass(frozen=True, slots=True)
class CodeCaptureContract:
    policy: RepositoryCodePolicy
    limits: RepositoryCodeLimits
    files: tuple[CodeCaptureFile, ...]
    directories: tuple[DirectoryMembership, ...]
    membership_sha256: str

    def __post_init__(self) -> None:
        _require_capture_types(self.policy, self.limits)
        _require_capture_files(self.files)
        if not _ordered_by_path(self.directories, DirectoryMembership):
            raise ValueError("directories must be an ordered DirectoryMembership tuple")
        _require_sha256(self.membership_sha256, "membership_sha256")


@dataclass(frozen=True, slots=True)
class CorpusSnapshot:
    sources: tuple[CapturedSource, ...]
    chunks: tuple[RetrievalChunk, ...]
    corpus_sha256: str
    policy: SnapshotPolicy
    collector_version: str = COLLECTOR_VERSION
    extractor_version: str = EXTRACTOR_VERSION
    code_capture: CodeCaptureContract | None = None

    @property
    def source_hashes(self) -> tuple[tuple[str, str], ...]:
        return tuple(
            (source.record.relative_path, source.record.sha256)
            for source in self.sources
        )


@dataclass(frozen=True, slots=True)
class _Candidate:
    path: Path
    relative: str
    kind: str
    project: str | None
    seal: tuple[_PathIdentity, ...]
    content: bytes | None = None


@dataclass(frozen=True, slots=True)
class _PathIdentity:
    path: Path
    device: int
    inode: int
    mode: int
    size: int
    ctime_ns: int
    attributes: int


def _sha256(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def _canonical_hash(value: object) -> str:
    encoded = json.dumps(
        value, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return _sha256(encoded)


def canonical_chunk_id(
    *,
    source_id: str,
    source_path: str,
    byte_start: int,
    byte_end: int,
    span_sha256: str,
    extractor_version: str = EXTRACTOR_VERSION,
) -> str:
    """Return the shared content-bound identity for one retrieval chunk."""
    return _canonical_hash(
        {
            "extractor": extractor_version,
            "parent": source_id,
            "path": source_path,
            "range": [byte_start, byte_end],
            "sha256": span_sha256,
        }
    )


def _require_capture_types(policy: object, limits: object) -> None:
    if not isinstance(policy, RepositoryCodePolicy):
        raise TypeError("policy must be RepositoryCodePolicy")
    if not isinstance(limits, RepositoryCodeLimits):
        raise TypeError("limits must be RepositoryCodeLimits")


def _unique_capture_identity(files: tuple) -> bool:
    file_paths = [item.relative_path.casefold() for item in files]
    source_ids = [item.source_id for item in files]
    return len(file_paths) == len(set(file_paths)) and len(source_ids) == len(set(source_ids))


def _require_capture_files(files: object) -> None:
    if not _ordered_by_path(files, CodeCaptureFile):
        raise ValueError("files must be an ordered CodeCaptureFile tuple")
    if not _unique_capture_identity(files):
        raise ValueError("files contain a path or source ID collision")


def _require_closed_source_mapping(record: object) -> Mapping[str, object]:
    if not isinstance(record, Mapping):
        raise TypeError("canonical source manifest entries must be SourceRecord values or objects")
    if set(record) != {"logical_id", "relative_path", "sha256"}:
        raise ValueError("canonical source manifest entries must be closed objects")
    return record


def _manifest_source_fields(
    record: SourceRecord | Mapping[str, object],
) -> tuple[object, object, object]:
    if isinstance(record, SourceRecord):
        return record.logical_id, record.relative_path, record.sha256
    mapping = _require_closed_source_mapping(record)
    return mapping["logical_id"], mapping["relative_path"], mapping["sha256"]


def _bounded_manifest_string(value: object) -> bool:
    return isinstance(value, str) and bool(value) and len(value) <= 4096


def _require_manifest_string(value: object, field: str) -> None:
    if _bounded_manifest_string(value):
        return
    raise ValueError(f"canonical source {field} must be a bounded non-empty string")


def _require_manifest_digest(digest: object) -> None:
    if isinstance(digest, str) and re.fullmatch(r"[0-9a-f]{64}", digest) is not None:
        return
    raise ValueError("canonical source sha256 must be a lowercase SHA-256 digest")


def _manifest_source(record: SourceRecord | Mapping[str, object]) -> dict[str, str]:
    logical_id, relative_path, digest = _manifest_source_fields(record)
    _require_manifest_string(logical_id, "logical_id")
    _require_manifest_string(relative_path, "relative_path")
    _require_manifest_digest(digest)
    return {"relative_path": relative_path, "sha256": digest, "logical_id": logical_id}


def _require_closed_policy_mapping(policy: object) -> Mapping[str, object]:
    if not isinstance(policy, Mapping):
        raise TypeError("canonical source manifest policy must be SnapshotPolicy or an object")
    if set(policy) != {"daily_paths", "code_roots", "include_historical", "as_of"}:
        raise ValueError("canonical source manifest policy must be a closed object")
    return policy


def _policy_manifest_fields(
    policy: SnapshotPolicy | Mapping[str, object],
) -> tuple[object, object, object, object]:
    if isinstance(policy, SnapshotPolicy):
        return policy.daily_paths, policy.code_roots, policy.include_historical, policy.as_of
    mapping = _require_closed_policy_mapping(policy)
    return (
        mapping["daily_paths"],
        mapping["code_roots"],
        mapping["include_historical"],
        mapping["as_of"],
    )


def _string_sequence(value: object) -> bool:
    if not isinstance(value, (list, tuple)):
        return False
    return all(isinstance(item, str) for item in value)


def _require_manifest_flags(include_historical: object, as_of: object) -> None:
    if not isinstance(include_historical, bool):
        raise ValueError("canonical include_historical must be boolean")
    if as_of is not None and not isinstance(as_of, str):
        raise ValueError("canonical as_of must be null or a string")


def _manifest_policy(policy: SnapshotPolicy | Mapping[str, object]) -> dict[str, object]:
    daily_paths, code_roots, include_historical, as_of = _policy_manifest_fields(policy)
    if not _string_sequence(daily_paths):
        raise ValueError("canonical daily_paths must be an array of strings")
    if not _string_sequence(code_roots):
        raise ValueError("canonical code_roots must be an array of strings")
    _require_manifest_flags(include_historical, as_of)
    return {
        "daily_paths": list(daily_paths),
        "code_roots": list(code_roots),
        "include_historical": include_historical,
        "as_of": as_of,
    }


def canonical_source_manifest(
    sources: Iterable[SourceRecord | Mapping[str, object]],
    policy: SnapshotPolicy | Mapping[str, object],
    *,
    collector_version: str = COLLECTOR_VERSION,
    extractor_version: str = EXTRACTOR_VERSION,
) -> dict[str, object]:
    """Return the one canonical source manifest shared by every generation consumer."""
    _require_manifest_versions(collector_version, extractor_version)
    entries = sorted(
        (_manifest_source(source) for source in sources),
        key=lambda item: (item["relative_path"], item["logical_id"]),
    )
    _require_unique_manifest_entries(entries)
    return {
        "collector": collector_version,
        "extractor": extractor_version,
        "policy": _manifest_policy(policy),
        "sources": entries,
    }


def canonical_source_manifest_sha256(
    sources: Iterable[SourceRecord | Mapping[str, object]],
    policy: SnapshotPolicy | Mapping[str, object],
    *,
    collector_version: str = COLLECTOR_VERSION,
    extractor_version: str = EXTRACTOR_VERSION,
) -> str:
    """Hash the shared canonical source manifest."""
    return _canonical_hash(
        canonical_source_manifest(
            sources,
            policy,
            collector_version=collector_version,
            extractor_version=extractor_version,
        )
    )


def _require_manifest_sources(value: Mapping[str, object]) -> list:
    sources = value["sources"]
    if not isinstance(sources, list):
        raise ValueError("canonical source manifest sources must be an array")
    return sources


def _require_closed_manifest(value: object) -> Mapping[str, object]:
    closed = isinstance(value, Mapping) and set(value) == {
        "collector",
        "extractor",
        "policy",
        "sources",
    }
    if not closed:
        raise ValueError("canonical source manifest must be a closed object")
    return value


def validate_canonical_source_manifest(value: object) -> dict[str, object]:
    """Validate and normalize one closed shared canonical source manifest."""
    manifest = _require_closed_manifest(value)
    normalized = canonical_source_manifest(
        _require_manifest_sources(manifest),
        manifest["policy"],
        collector_version=manifest["collector"],
        extractor_version=manifest["extractor"],
    )
    if manifest != normalized:
        raise ValueError("canonical source manifest must use deterministic source ordering")
    return normalized


def _positive_limit(value: object, name: str, *, allow_zero: bool = False) -> int:
    minimum = 0 if allow_zero else 1
    if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
        raise ValueError(f"{name} must be an integer >= {minimum}")
    return value


def _require_monotonic(deadline: object) -> float:
    if isinstance(deadline, bool) or not isinstance(deadline, (int, float)):
        raise ValueError("deadline must be a monotonic timestamp")
    return float(deadline)


def _require_seconds(value: object) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)) or value < 0:
        raise ValueError("deadline_seconds must be non-negative")
    return float(value)


def _deadline_value(deadline: float | None, deadline_seconds: float | None) -> float:
    if deadline is not None and deadline_seconds is not None:
        raise ValueError("deadline and deadline_seconds are mutually exclusive")
    if deadline is not None:
        return _require_monotonic(deadline)
    seconds = DEFAULT_DEADLINE_SECONDS if deadline_seconds is None else deadline_seconds
    return time.monotonic() + _require_seconds(seconds)


def _check_deadline(deadline: float) -> None:
    if time.monotonic() >= deadline:
        raise TimeoutError("corpus collection deadline reached")


def _check_processing_stop(
    deadline: float | None, cancelled: Callable[[], bool] | None
) -> None:
    if bool(cancelled and cancelled()):
        raise TimeoutError("corpus collection cancelled")
    if deadline is not None:
        _check_deadline(deadline)


def _under_prefix(normalized: str, prefixes: tuple[str, ...]) -> bool:
    return any(
        normalized == prefix or normalized.startswith(prefix + "/") for prefix in prefixes
    )


def _valid_source_path(raw: str, pure: PurePosixPath, normalized: str) -> bool:
    if not raw or "\\" in raw:
        return False
    if normalized != raw:
        return False
    return _relative_parts_ok(pure)


def _relative_posix(value: str | Path, *, prefixes: tuple[str, ...]) -> str:
    raw = str(value)
    pure = PurePosixPath(raw)
    normalized = unicodedata.normalize("NFC", pure.as_posix())
    if not _valid_source_path(raw, pure, normalized) or not _under_prefix(normalized, prefixes):
        raise ValueError("source path must be a normalized relative POSIX path")
    return normalized


def _windows_shaped(raw: str) -> bool:
    windows_path = PureWindowsPath(raw)
    return "\\" in raw or ":" in raw or bool(windows_path.drive or windows_path.root)


def _code_root(value: str | Path) -> str:
    raw = str(value)
    if _windows_shaped(raw):
        raise ValueError("code root must be a normalized approved relative POSIX path")
    try:
        return _relative_posix(value, prefixes=tuple(sorted(APPROVED_CODE_ROOTS)))
    except ValueError as exc:
        raise ValueError(
            "code root must be a normalized approved relative POSIX path"
        ) from exc


def _safe_info(path: Path) -> os.stat_result:
    info = path.lstat()
    if path.is_symlink() or bool(
        getattr(info, "st_file_attributes", 0)
        & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    ):
        raise PermissionError(f"unsafe corpus path: {path}")
    return info


# Only the two attribute bits that change what an ancestor *is*. Windows sets
# and clears others — indexing, offline, pinning — while a path is being walked,
# and a seal that compares the whole DWORD reads that as a swapped ancestor.
_SEAL_ATTRIBUTES = 0x10 | 0x400  # FILE_ATTRIBUTE_DIRECTORY, _REPARSE_POINT


def _identity(path: Path, info: os.stat_result) -> _PathIdentity:
    return _PathIdentity(
        path=path,
        device=info.st_dev,
        inode=info.st_ino,
        mode=info.st_mode,
        size=info.st_size,
        ctime_ns=info.st_ctime_ns,
        attributes=(getattr(info, "st_file_attributes", 0) or 0) & _SEAL_ATTRIBUTES,
    )


def _seal_path(
    vault: Path,
    path: Path,
    *,
    target_directory: bool,
    max_components: int,
) -> tuple[_PathIdentity, ...]:
    seal = _build_path_seal(
        vault,
        path,
        target_directory=target_directory,
        max_components=max_components,
    )
    _verify_seal(seal, changed_error=PermissionError)
    return seal


def _relative_within(vault: Path, path: Path) -> Path:
    try:
        return path.relative_to(vault)
    except ValueError as exc:
        raise PermissionError("corpus path escapes the resolved vault") from exc


def _component_paths(vault: Path, relative: Path) -> list[Path]:
    components = [vault]
    current = vault
    for part in relative.parts:
        current /= part
        components.append(current)
    return components


def _require_component_kind(
    component: Path, info: os.stat_result, *, expect_directory: bool, allow_regular: bool
) -> None:
    if expect_directory != stat.S_ISDIR(info.st_mode):
        expected = "directory" if expect_directory else "regular file"
        raise PermissionError(f"corpus path component must be a {expected}: {component}")
    if allow_regular and not stat.S_ISREG(info.st_mode):
        raise PermissionError(f"corpus source must be a regular file: {component}")


def _require_inside(component: Path, vault: Path) -> None:
    try:
        component.resolve(strict=True).relative_to(vault)
    except ValueError as exc:
        raise PermissionError("corpus path resolves outside the vault") from exc


def _sealed_component(
    component: Path, vault: Path, *, is_target: bool, target_directory: bool
) -> _PathIdentity:
    info = _safe_info(component)
    expect_directory = not is_target or target_directory
    _require_component_kind(
        component,
        info,
        expect_directory=expect_directory,
        allow_regular=is_target and not target_directory,
    )
    _require_inside(component, vault)
    return _identity(component, info)


def _build_path_seal(
    vault: Path,
    path: Path,
    *,
    target_directory: bool,
    max_components: int,
) -> tuple[_PathIdentity, ...]:
    relative = _relative_within(vault, path)
    if len(relative.parts) > max_components:
        raise ValueError("corpus ancestor depth limit exceeded")
    components = _component_paths(vault, relative)
    last = len(components) - 1
    return tuple(
        _sealed_component(
            component,
            vault,
            is_target=index == last,
            target_directory=target_directory,
        )
        for index, component in enumerate(components)
    )


def _open_sealed_posix_path(
    vault: Path,
    path: Path,
    *,
    target_directory: bool,
    max_components: int,
) -> tuple[tuple[_PathIdentity, ...], int]:
    seal = _build_path_seal(
        vault,
        path,
        target_directory=target_directory,
        max_components=max_components,
    )
    descriptor = _open_descriptor_chain(seal, changed_error=PermissionError)
    return seal, descriptor


def _identity_delta(expected: _PathIdentity, current: _PathIdentity) -> str:
    """Name the fields that moved, so the refusal can be acted on."""
    fields = ("device", "inode", "mode", "size", "ctime_ns", "attributes")
    changed = [
        f"{name}: {getattr(expected, name)} -> {getattr(current, name)}"
        for name in fields
        if getattr(expected, name) != getattr(current, name)
    ]
    return ", ".join(changed) or "identical fields"


def _verify_seal(
    seal: tuple[_PathIdentity, ...], *, changed_error: type[Exception] = CorpusChanged
) -> None:
    for expected in seal:
        try:
            current = _identity(expected.path, _safe_info(expected.path))
        except (OSError, PermissionError) as exc:
            raise changed_error(f"corpus ancestor changed: {expected.path}") from exc
        if current != expected:
            raise changed_error(
                f"corpus ancestor changed: {expected.path} ({_identity_delta(expected, current)})"
            )
    _verify_descriptor_chain(seal, changed_error=changed_error)


def _verify_descriptor_chain(
    seal: tuple[_PathIdentity, ...], *, changed_error: type[Exception]
) -> None:
    if os.name != "posix" or not seal:
        return
    descriptor = _open_descriptor_chain(seal, changed_error=changed_error)
    os.close(descriptor)


def _child_descriptor_flags(expected: _PathIdentity, flags: int) -> int:
    if stat.S_ISDIR(expected.mode):
        return flags | getattr(os, "O_DIRECTORY", 0)
    return flags


def _open_sealed_root(expected: _PathIdentity, flags: int, changed_error) -> int:
    descriptor = os.open(expected.path, flags | getattr(os, "O_DIRECTORY", 0))
    if _identity(expected.path, os.fstat(descriptor)) != expected:
        os.close(descriptor)
        raise changed_error(f"corpus ancestor changed: {expected.path}")
    return descriptor


def _descend(descriptor: int, expected: _PathIdentity, flags: int, changed_error) -> int:
    """Open the next component; the descriptor handed in is closed either way."""
    try:
        child = os.open(
            expected.path.name, _child_descriptor_flags(expected, flags), dir_fd=descriptor
        )
    finally:
        os.close(descriptor)
    if _identity(expected.path, os.fstat(child)) != expected:
        os.close(child)
        raise changed_error(f"corpus ancestor changed: {expected.path}")
    return child


def _open_descriptor_chain(
    seal: tuple[_PathIdentity, ...], *, changed_error: type[Exception]
) -> int:
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    descriptor = -1
    try:
        descriptor = _open_sealed_root(seal[0], flags, changed_error)
        for expected in seal[1:]:
            handed, descriptor = descriptor, -1
            descriptor = _descend(handed, expected, flags, changed_error)
        result = descriptor
        descriptor = -1
        return result
    except OSError as exc:
        raise changed_error("corpus ancestor changed during descriptor traversal") from exc
    finally:
        if descriptor >= 0:
            os.close(descriptor)


def _same_opened_object(left: os.stat_result, right: os.stat_result) -> bool:
    return (
        left.st_dev,
        left.st_ino,
        left.st_mode,
        left.st_size,
        left.st_mtime_ns,
        left.st_ctime_ns,
    ) == (
        right.st_dev,
        right.st_ino,
        right.st_mode,
        right.st_size,
        right.st_mtime_ns,
        right.st_ctime_ns,
    )


def _same_descriptor_identity(left: os.stat_result, right: os.stat_result) -> bool:
    return (left.st_dev, left.st_ino, stat.S_IFMT(left.st_mode)) == (
        right.st_dev,
        right.st_ino,
        stat.S_IFMT(right.st_mode),
    )


def _descriptor_flags(*, directory: bool) -> int:
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    if directory:
        flags |= getattr(os, "O_DIRECTORY", 0)
    return flags


def _require_bounded_size(size: int, max_bytes: int) -> None:
    if size > max_bytes:
        raise ValueError(f"corpus source exceeds {max_bytes} bytes")


def _read_chunks(descriptor: int, max_bytes: int) -> bytes:
    chunks: list[bytes] = []
    remaining = max_bytes + 1
    while remaining:
        chunk = os.read(descriptor, min(remaining, 1024 * 1024))
        if not chunk:
            break
        chunks.append(chunk)
        remaining -= len(chunk)
    return b"".join(chunks)


def _read_bounded_descriptor(descriptor: int, max_bytes: int) -> bytes:
    before = os.fstat(descriptor)
    if not stat.S_ISREG(before.st_mode):
        raise PermissionError("corpus source descriptor must be a regular file")
    _require_bounded_size(before.st_size, max_bytes)
    content = _read_chunks(descriptor, max_bytes)
    _require_bounded_size(len(content), max_bytes)
    if not _same_opened_object(before, os.fstat(descriptor)):
        raise CorpusChanged("corpus source changed during descriptor read")
    return content


class _Discovery:
    def __init__(
        self,
        vault: Path,
        *,
        max_files: int,
        max_entries: int,
        max_directories: int,
        max_depth: int,
        max_file_bytes: int,
        max_total_bytes: int,
        deadline: float,
        include_archives: bool,
    ) -> None:
        self.vault = vault
        self.max_files = max_files
        self.max_entries = max_entries
        self.max_directories = max_directories
        self.max_depth = max_depth
        self.max_file_bytes = max_file_bytes
        self.max_total_bytes = max_total_bytes
        self.deadline = deadline
        self.include_archives = include_archives
        self.entries = 0
        self.directories = 0
        self.total_bytes = 0
        self.candidates: dict[str, _Candidate] = {}

    def add(self, path: Path, kind: str, project: str | None = None) -> None:
        _check_deadline(self.deadline)
        if os.name == "posix":
            _, descriptor = _open_sealed_posix_path(
                self.vault,
                path,
                target_directory=False,
                max_components=self.max_depth + 3,
            )
            try:
                content = _read_bounded_descriptor(descriptor, self.max_file_bytes)
            finally:
                os.close(descriptor)
            self._store(path, kind, project, (), content)
            return
        seal = _seal_path(
            self.vault,
            path,
            target_directory=False,
            max_components=self.max_depth + 3,
        )
        self._store(path, kind, project, seal, None)

    def _store(
        self,
        path: Path,
        kind: str,
        project: str | None,
        seal: tuple[_PathIdentity, ...],
        content: bytes | None,
    ) -> None:
        relative = unicodedata.normalize("NFC", path.relative_to(self.vault).as_posix())
        self._require_unseen(relative)
        self._count_bytes(content)
        self.candidates[relative] = _Candidate(path, relative, kind, project, seal, content)
        if len(self.candidates) > self.max_files:
            raise ValueError("corpus file limit exceeded")

    def _require_unseen(self, relative: str) -> None:
        if relative in self.candidates:
            raise ValueError(f"duplicate corpus source path: {relative}")

    def _count_bytes(self, content: bytes | None) -> None:
        if content is None:
            return
        self.total_bytes += len(content)
        if self.total_bytes > self.max_total_bytes:
            raise ValueError("corpus total byte limit exceeded")

    def walk(self, root: Path, kind: str) -> None:
        if not root.exists():
            return
        if os.name == "posix":
            self._walk_posix(root, kind)
            return
        self._walk_windows(root, kind)

    def _directory_seal(self, path: Path) -> tuple[_PathIdentity, ...]:
        return _seal_path(
            self.vault,
            path,
            target_directory=True,
            max_components=self.max_depth + 3,
        )

    def _count_directory(self, depth: int) -> None:
        self.directories += 1
        if self.directories > self.max_directories:
            raise ValueError("corpus directory limit exceeded")
        if depth > self.max_depth:
            raise ValueError("corpus depth limit exceeded")

    def _count_entry(self) -> None:
        self.entries += 1
        if self.entries > self.max_entries:
            raise ValueError("corpus traversal entry limit exceeded")

    def _directory_excluded(self, name: str) -> bool:
        if name in SKIP_DIRECTORIES:
            return True
        if name in ARCHIVE_DIRECTORIES:
            return not self.include_archives
        return name.startswith(".")

    @staticmethod
    def _project_of(path: Path, root: Path, kind: str) -> str | None:
        if kind != "project":
            return None
        parts = path.relative_to(root).parts
        if len(parts) > 1:
            return parts[0]
        return None

    def _walk_windows(self, root: Path, kind: str) -> None:
        stack = [(root, 0, self._directory_seal(root))]
        while stack:
            current, depth, current_seal = stack.pop()
            children = self._walk_windows_directory(root, current, depth, current_seal, kind)
            stack.extend((child, depth + 1, seal) for child, seal in reversed(children))

    def _windows_entries(self, current: Path) -> list:
        entries = []
        with os.scandir(current) as iterator:
            for entry in iterator:
                _check_deadline(self.deadline)
                self._count_entry()
                entries.append(entry)
        return entries

    def _walk_windows_directory(
        self,
        root: Path,
        current: Path,
        depth: int,
        current_seal: tuple[_PathIdentity, ...],
        kind: str,
    ) -> list:
        _check_deadline(self.deadline)
        _verify_seal(current_seal)
        self._count_directory(depth)
        entries = self._windows_entries(current)
        _verify_seal(current_seal)
        children = [
            child
            for child in (
                self._windows_entry(root, entry, depth, kind)
                for entry in sorted(entries, key=lambda item: item.name)
            )
            if child is not None
        ]
        _verify_seal(current_seal)
        return children

    def _windows_entry(self, root: Path, entry: os.DirEntry, depth: int, kind: str):
        """The child directory to descend into, or None once the file is stored."""
        _check_deadline(self.deadline)
        path = Path(entry.path)
        info = entry.stat(follow_symlinks=False)
        _require_safe_entry(path, info, symlink=entry.is_symlink())
        if stat.S_ISDIR(info.st_mode):
            return self._windows_child(path, entry.name, depth)
        if stat.S_ISREG(info.st_mode) and self._eligible(path, kind):
            self.add(path, kind, self._project_of(path, root, kind))
        return None

    def _windows_child(self, path: Path, name: str, depth: int):
        if self._directory_excluded(name):
            return None
        if depth >= self.max_depth:
            raise ValueError("corpus depth limit exceeded")
        return (path, self._directory_seal(path))

    def _walk_posix(self, root: Path, kind: str) -> None:
        _, descriptor = _open_sealed_posix_path(
            self.vault,
            root,
            target_directory=True,
            max_components=self.max_depth + 3,
        )
        try:
            self._walk_posix_directory(root, root, 0, descriptor, kind)
        finally:
            os.close(descriptor)

    def _posix_entries(self, descriptor: int) -> list:
        entries = []
        with os.scandir(descriptor) as iterator:
            for entry in iterator:
                _check_deadline(self.deadline)
                self._count_entry()
                entries.append(
                    (
                        entry.name,
                        os.stat(entry.name, dir_fd=descriptor, follow_symlinks=False),
                    )
                )
        return entries

    def _walk_posix_directory(
        self,
        root: Path,
        current: Path,
        depth: int,
        descriptor: int,
        kind: str,
    ) -> None:
        _check_deadline(self.deadline)
        opened_directory = os.fstat(descriptor)
        if not stat.S_ISDIR(opened_directory.st_mode):
            raise PermissionError("corpus traversal descriptor must be a directory")
        self._count_directory(depth)
        entries = self._posix_entries(descriptor)
        if not _same_descriptor_identity(opened_directory, os.fstat(descriptor)):
            raise CorpusChanged("corpus directory descriptor changed during traversal")
        for name, info in sorted(entries, key=lambda item: item[0]):
            self._posix_entry(root, current, depth, descriptor, kind, name, info)

    def _posix_entry(
        self,
        root: Path,
        current: Path,
        depth: int,
        descriptor: int,
        kind: str,
        name: str,
        info: os.stat_result,
    ) -> None:
        _check_deadline(self.deadline)
        path = current / name
        _require_safe_entry(path, info, symlink=stat.S_ISLNK(info.st_mode))
        if stat.S_ISDIR(info.st_mode):
            self._posix_child(root, path, depth, descriptor, kind, name, info)
            return
        if stat.S_ISREG(info.st_mode) and self._eligible(path, kind):
            self._posix_source(root, path, descriptor, kind, name, info)

    def _posix_child(
        self,
        root: Path,
        path: Path,
        depth: int,
        descriptor: int,
        kind: str,
        name: str,
        info: os.stat_result,
    ) -> None:
        if self._directory_excluded(name):
            return
        if depth >= self.max_depth:
            raise ValueError("corpus depth limit exceeded")
        child = os.open(name, _descriptor_flags(directory=True), dir_fd=descriptor)
        try:
            if not _same_descriptor_identity(info, os.fstat(child)):
                raise CorpusChanged("corpus child directory changed before open")
            self._walk_posix_directory(root, path, depth + 1, child, kind)
        finally:
            os.close(child)

    def _posix_source(
        self,
        root: Path,
        path: Path,
        descriptor: int,
        kind: str,
        name: str,
        info: os.stat_result,
    ) -> None:
        source = os.open(name, _descriptor_flags(directory=False), dir_fd=descriptor)
        try:
            if not _same_opened_object(info, os.fstat(source)):
                raise CorpusChanged("corpus source changed before descriptor open")
            content = _read_bounded_descriptor(source, self.max_file_bytes)
        finally:
            os.close(source)
        self._store(path, kind, self._project_of(path, root, kind), (), content)

    @staticmethod
    def _eligible(path: Path, kind: str) -> bool:
        if kind == "note":
            return path.suffix.casefold() == ".md" and path.name not in EDITORIAL_NAMES
        if kind == "project":
            return path.name in PROJECT_FILES
        return True


def _walk_knowledge(discovery: _Discovery, vault: Path) -> None:
    discovery.walk(vault / "knowledge/notes", "note")
    discovery.walk(vault / "knowledge/projects", "project")
    # Session records are deliberately NOT collected. They are kept verbatim on
    # disk, they are read by the nightly consolidation, and they are greppable —
    # but they are not part of the retrieval corpus, because measurement says
    # they take it over: importing 236 past sessions (about 10 MB of the same
    # conversations the pages were compiled from) moved the vault stand from
    # hit@5 0.7 to 0.0, and neither a below-neutral trust weight nor ordering
    # compiled pages first brought it back past 0.4 — by then the decision page
    # was no longer in the candidate pool at all.
    #
    # What would make them safe to index is a second tier consulted when the
    # compiled pages do not answer, or a per-source quota in the pool. Neither is
    # built, so the honest state is: kept, not indexed. See MEM-01 in
    # docs/DEVELOPER-AUDIT-STATUS-2026-08-18.md.


def _existing_path(vault: Path, relative: str) -> Path:
    path = vault.joinpath(*PurePosixPath(relative).parts)
    if not path.exists():
        raise FileNotFoundError(relative)
    return path


def _add_daily_paths(
    discovery: _Discovery, vault: Path, policy: SnapshotPolicy, deadline: float
) -> None:
    for relative in policy.daily_paths:
        _check_deadline(deadline)
        discovery.add(_existing_path(vault, relative), "daily")


def _add_code_root(discovery: _Discovery, path: Path, relative: str) -> None:
    info = _safe_info(path)
    if stat.S_ISDIR(info.st_mode):
        discovery.walk(path, "code")
        return
    if not stat.S_ISREG(info.st_mode):
        raise PermissionError(f"code root must be a regular path: {relative}")
    discovery.add(path, "code")


def _add_code_roots(
    discovery: _Discovery, vault: Path, policy: SnapshotPolicy, deadline: float
) -> None:
    for relative in policy.code_roots:
        _check_deadline(deadline)
        _add_code_root(discovery, _existing_path(vault, relative), relative)


def _discover(vault: Path, policy: SnapshotPolicy, deadline: float) -> tuple[_Candidate, ...]:
    discovery = _Discovery(
        vault,
        max_files=policy.max_files,
        max_entries=policy.max_entries,
        max_directories=policy.max_directories,
        max_depth=policy.max_depth,
        max_file_bytes=policy.max_file_bytes,
        max_total_bytes=policy.max_total_bytes,
        deadline=deadline,
        include_archives=policy.include_historical or policy.as_of is not None,
    )
    _walk_knowledge(discovery, vault)
    _add_daily_paths(discovery, vault, policy, deadline)
    _add_code_roots(discovery, vault, policy, deadline)
    return tuple(discovery.candidates[key] for key in sorted(discovery.candidates))


def _decodes_as_utf8(content: bytes) -> bool:
    """Whether these bytes are text at all; a binary file is not a source.

    It is still hashed, so membership checks still see it, but it is left out
    of the corpus. One stray binary under a code root must not be able to fail
    the whole generation.
    """
    try:
        content.decode("utf-8", errors="strict")
    except UnicodeDecodeError:
        return False
    return True


def _line_spans(content: bytes, start: int = 0) -> Iterable[tuple[int, int]]:
    offset = start
    while offset < len(content):
        newline = content.find(b"\n", offset)
        end = len(content) if newline < 0 else newline + 1
        yield offset, end
        offset = end


def _frontmatter_close(
    content: bytes,
    lines,
    deadline: float | None,
    cancelled: Callable[[], bool] | None,
) -> tuple[int, int] | None:
    for line_start, line_end in lines:
        _check_processing_stop(deadline, cancelled)
        if content[line_start:line_end].strip() == b"---":
            return line_start, line_end
    return None


def _frontmatter_mapping(raw: bytes) -> dict[str, Any]:
    value = yaml.safe_load(raw.decode("utf-8", errors="strict"))
    if not isinstance(value, Mapping):
        raise ValueError("frontmatter must be a mapping")
    return dict(value)


def _frontmatter(
    content: bytes,
    *,
    deadline: float | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> tuple[dict[str, Any], int]:
    content.decode("utf-8", errors="strict")
    lines = iter(_line_spans(content))
    first = next(lines, None)
    if first is None or content[first[0] : first[1]].strip() != b"---":
        return {}, 0
    closing = _frontmatter_close(content, lines, deadline, cancelled)
    if closing is None:
        raise ValueError("unterminated YAML frontmatter")
    return _frontmatter_mapping(content[first[1] : closing[0]]), closing[1]


def _utc_text(value: datetime) -> str:
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def _dated_metadata_text(value: date | datetime) -> str:
    if isinstance(value, datetime):
        return _utc_text(value)
    return value.isoformat()


def _scalar_metadata_text(value: object) -> str:
    if isinstance(value, (str, int, float, bool)):
        return str(value)
    raise ValueError("corpus metadata values must be scalar")


def _metadata_value(value: object) -> str | None:
    if value is None:
        return None
    if isinstance(value, (date, datetime)):
        return _dated_metadata_text(value)
    return _scalar_metadata_text(value)


_DEFAULT_SOURCE_TYPES = {
    "note": "note",
    "daily": "daily-evidence",
    "session": "session-evidence",
    "code": "code",
}


# Prose under a code root is commentary, not code: research notes, status
# registers, design write-ups. Calling it `code` gave it the neutral trust
# weight, and on this vault the audit register — one long Russian document that
# discusses every decision — then outranked the decision pages themselves.
_PROSE_SUFFIXES = frozenset({".md", ".markdown", ".rst", ".txt"})


def _default_source_type(candidate: _Candidate) -> str:
    if candidate.kind == "project":
        return _project_source_type(candidate)
    if candidate.kind == "code" and candidate.path.suffix.casefold() in _PROSE_SUFFIXES:
        return "doc"
    return _DEFAULT_SOURCE_TYPES[candidate.kind]


def _project_source_type(candidate: _Candidate) -> str:
    if candidate.path.name == "state.md":
        return "project-state"
    return "project-context"


def _validity_mapping(frontmatter: Mapping[str, object]) -> Mapping[str, object]:
    validity = frontmatter.get("validity", {})
    if validity is None:
        return {}
    if not isinstance(validity, Mapping):
        raise ValueError("validity metadata must be a mapping")
    return validity


def _metadata_status(frontmatter: Mapping[str, object]) -> str:
    return (_metadata_value(frontmatter.get("status")) or "active").casefold()


def _metadata_language(frontmatter: Mapping[str, object]) -> str | None:
    language = _metadata_value(frontmatter.get("language") or frontmatter.get("lang"))
    if not language:
        return None
    return language.casefold()


def _metadata(frontmatter: Mapping[str, object], candidate: _Candidate) -> SourceMetadata:
    validity = _validity_mapping(frontmatter)
    return SourceMetadata(
        type=_metadata_value(frontmatter.get("type")) or _default_source_type(candidate),
        project=_metadata_value(frontmatter.get("project")) or candidate.project,
        authority=_metadata_value(
            frontmatter.get("source_authority", frontmatter.get("authority"))
        ),
        confidence=_metadata_value(frontmatter.get("confidence")),
        status=_metadata_status(frontmatter),
        valid_from=_metadata_value(
            frontmatter.get("valid_from", validity.get("from"))
        ),
        valid_to=_metadata_value(frontmatter.get("valid_to", validity.get("to"))),
        language=_metadata_language(frontmatter),
    )


def _parsed_iso(text: str) -> datetime:
    normalized = text.strip()
    if normalized.endswith("Z"):
        normalized = normalized[:-1] + "+00:00"
    try:
        return datetime.fromisoformat(normalized)
    except ValueError:
        return datetime.combine(date.fromisoformat(normalized), datetime_time.min)


def _dated_naive_datetime(value: date | datetime) -> datetime:
    if isinstance(value, datetime):
        return value
    return datetime.combine(value, datetime_time.min)


def _naive_datetime(value: str | date | datetime) -> datetime:
    if isinstance(value, (date, datetime)):
        return _dated_naive_datetime(value)
    if isinstance(value, str):
        return _parsed_iso(value)
    raise ValueError("as_of and validity values must be ISO dates or datetimes")


def _as_datetime(value: str | date | datetime | None) -> datetime | None:
    if value is None:
        return None
    result = _naive_datetime(value)
    if result.tzinfo is None:
        result = result.replace(tzinfo=timezone.utc)
    return result.astimezone(timezone.utc)


def _within_validity(metadata: SourceMetadata, instant: datetime) -> bool:
    start = _as_datetime(metadata.valid_from)
    end = _as_datetime(metadata.valid_to)
    if start is not None and start > instant:
        return False
    return end is None or instant < end


def _included(metadata: SourceMetadata, policy: SnapshotPolicy) -> bool:
    if policy.as_of is None:
        return policy.include_historical or not is_retired(metadata.status)
    instant = _as_datetime(policy.as_of)
    assert instant is not None
    return _within_validity(metadata, instant)


def _dominant(count: int, others: tuple[int, ...]) -> bool:
    return bool(count) and all(count >= other for other in others)


def _latin_only(latin: int, cyrillic: int, han: int) -> bool:
    return latin >= 3 and not cyrillic and not han


def _dominant_script_language(cyrillic: int, han: int, latin: int) -> str | None:
    if _dominant(cyrillic, (han, latin)):
        return "ru"
    if _dominant(han, (cyrillic, latin)):
        return "zh"
    return None


def _infer_language(text: str) -> str | None:
    cyrillic = len(_CYRILLIC.findall(text))
    han = len(_HAN.findall(text))
    latin = len(_LATIN.findall(text))
    dominant = _dominant_script_language(cyrillic, han, latin)
    if dominant is not None:
        return dominant
    return "en" if _latin_only(latin, cyrillic, han) else None


def _classify_language(*, explicit: str | None, path: Path, text: str) -> str | None:
    return explicit or language_for_path(path) or _infer_language(text)


def _clean_heading(raw: bytes | None) -> str:
    title = (raw or b"").decode("utf-8", errors="strict").strip()
    return _CLOSING_HASHES.sub("", title)


def _closing_fence(body: bytes, character: bytes, length: int) -> bool:
    pattern = (
        rb"[ ]{0,3}"
        + re.escape(character)
        + rb"{" + str(length).encode("ascii") + rb",}[ \t]*"
    )
    return re.fullmatch(pattern, body) is not None


def _opening_fence(body: bytes):
    """The fence that opens a block, or None — a backtick in the info string is not one."""
    opening = _FENCE.fullmatch(body)
    if opening is None:
        return None
    if opening.group(1).startswith(b"`") and b"`" in opening.group(2):
        return None
    return opening


class _HeadingScan:
    """The fence state machine that decides which lines may be headings."""

    def __init__(self) -> None:
        self.character: bytes | None = None
        self.length = 0
        self.headings: list[re.Match[bytes]] = []

    def line(self, content: bytes, offset: int, end: int) -> None:
        body = content[offset:end].rstrip(b"\r\n")
        if self.character is not None:
            self._maybe_close(body)
            return
        opening = _opening_fence(body)
        if opening is not None:
            self.character = opening.group(1)[:1]
            self.length = len(opening.group(1))
            return
        self._maybe_heading(content, offset, end)

    def _maybe_close(self, body: bytes) -> None:
        if _closing_fence(body, self.character, self.length):
            self.character = None
            self.length = 0

    def _maybe_heading(self, content: bytes, offset: int, end: int) -> None:
        heading = _HEADING.match(content, offset, end)
        if heading is None:
            return
        if len(self.headings) >= MAX_CORPUS_HEADINGS:
            raise ValueError("corpus heading row ceiling exceeded")
        self.headings.append(heading)


def _markdown_headings(
    content: bytes,
    start: int,
    *,
    deadline: float | None,
    cancelled: Callable[[], bool] | None,
) -> list[re.Match[bytes]]:
    scan = _HeadingScan()
    for offset, end in _line_spans(content, start):
        _check_processing_stop(deadline, cancelled)
        scan.line(content, offset, end)
    return scan.headings


def _headings_when_enabled(
    content: bytes,
    searchable_start: int,
    heading_enabled: bool,
    deadline: float | None,
    cancelled: Callable[[], bool] | None,
) -> list[re.Match[bytes]]:
    if not heading_enabled:
        return []
    return _markdown_headings(
        content, searchable_start, deadline=deadline, cancelled=cancelled
    )


def _leading_span(
    content: bytes, searchable_start: int, first_heading: int
) -> list[tuple[int, int, tuple[str, ...]]]:
    if content[searchable_start:first_heading].strip():
        return [(searchable_start, first_heading, ())]
    return []


def _heading_end(headings: list[re.Match[bytes]], index: int, content: bytes) -> int:
    if index + 1 < len(headings):
        return headings[index + 1].start()
    return len(content)


def _updated_ancestry(
    ancestry: list[tuple[int, str]], level: int, title: str
) -> list[tuple[int, str]]:
    kept = [item for item in ancestry if item[0] < level]
    kept.append((level, title))
    return kept


def _append_heading_span(
    spans: list, content: bytes, heading: re.Match[bytes], end: int, ancestry: list
) -> None:
    if not content[heading.start():end].strip():
        return
    if len(spans) >= MAX_CORPUS_CHUNKS:
        raise ValueError("corpus chunk row ceiling exceeded")
    spans.append((heading.start(), end, tuple(item[1] for item in ancestry)))


def _retrieval_spans(
    content: bytes,
    searchable_start: int,
    *,
    heading_enabled: bool,
    deadline: float | None,
    cancelled: Callable[[], bool] | None,
) -> tuple[tuple[int, int, tuple[str, ...]], ...]:
    headings = _headings_when_enabled(
        content, searchable_start, heading_enabled, deadline, cancelled
    )
    first_heading = headings[0].start() if headings else len(content)
    spans = _leading_span(content, searchable_start, first_heading)
    ancestry: list[tuple[int, str]] = []
    for index, heading in enumerate(headings):
        _check_processing_stop(deadline, cancelled)
        ancestry = _updated_ancestry(
            ancestry, len(heading.group(1)), _clean_heading(heading.group(2))
        )
        _append_heading_span(
            spans, content, heading, _heading_end(headings, index, content), ancestry
        )
    return tuple(spans)


def _markdown_head(
    source_path: str,
    content: bytes,
    deadline: float | None,
    cancelled: Callable[[], bool] | None,
) -> tuple[bool, int, dict[str, Any]]:
    """(is markdown, where the searchable text starts, the frontmatter)."""
    is_markdown = PurePosixPath(source_path).suffix.casefold() == ".md"
    if not is_markdown:
        content.decode("utf-8", errors="strict")
        return False, 0, {}
    frontmatter, searchable_start = _frontmatter(
        content, deadline=deadline, cancelled=cancelled
    )
    return True, searchable_start, frontmatter


def canonical_retrieval_spans(
    source_path: str,
    content: bytes,
    *,
    deadline: float | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> tuple[tuple[int, int, tuple[str, ...]], ...]:
    """Return the shared canonical chunk ranges for captured source bytes."""
    if not isinstance(source_path, str) or not source_path:
        raise ValueError("source_path must be a non-empty string")
    if not isinstance(content, bytes) or len(content) > MAX_CORPUS_FILE_BYTES:
        raise ValueError("captured retrieval source must be bounded bytes")
    is_markdown, searchable_start, _frontmatter_value = _markdown_head(
        source_path, content, deadline, cancelled
    )
    return _retrieval_spans(
        content,
        searchable_start,
        heading_enabled=is_markdown,
        deadline=deadline,
        cancelled=cancelled,
    )


def _chunks(
    source: SourceRecord,
    metadata: SourceMetadata,
    content: bytes,
    searchable_start: int,
    *,
    heading_enabled: bool = True,
    extractor_version: str = EXTRACTOR_VERSION,
    deadline: float | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> tuple[RetrievalChunk, ...]:
    result = []
    spans = _retrieval_spans(
        content,
        searchable_start,
        heading_enabled=heading_enabled,
        deadline=deadline,
        cancelled=cancelled,
    )
    for start, end, heading_ancestry in spans:
        _check_processing_stop(deadline, cancelled)
        span = content[start:end]
        text = span.decode("utf-8", errors="strict")
        span_hash = _sha256(span)
        chunk_id = canonical_chunk_id(
            source_id=source.logical_id,
            source_path=source.relative_path,
            byte_start=start,
            byte_end=end,
            span_sha256=span_hash,
            extractor_version=extractor_version,
        )
        result.append(
            RetrievalChunk(
                id=chunk_id,
                source_id=source.logical_id,
                source_path=source.relative_path,
                parent_page=source.relative_path,
                heading_ancestry=heading_ancestry,
                byte_start=start,
                byte_end=end,
                line_start=content.count(b"\n", 0, start) + 1,
                line_end=content.count(b"\n", 0, end) + 1,
                text=text,
                source_sha256=source.sha256,
                span_sha256=span_hash,
                type=metadata.type,
                project=metadata.project,
                authority=metadata.authority,
                confidence=metadata.confidence,
                status=metadata.status,
                valid_from=metadata.valid_from,
                valid_to=metadata.valid_to,
                language=source.language or _infer_language(text),
            )
        )
    return tuple(result)


_SOURCE_KIND_PREFIXES = (
    (("knowledge", "raw", "sessions"), "session"),
    (("knowledge", "notes"), "note"),
    (("knowledge", "daily"), "daily"),
)


def _project_part(path: PurePosixPath) -> str | None:
    if len(path.parts) > 3:
        return path.parts[2]
    return None


def _source_kind(path: PurePosixPath) -> tuple[str, str | None]:
    for prefix, kind in _SOURCE_KIND_PREFIXES:
        if path.parts[: len(prefix)] == prefix:
            return kind, None
    if path.parts[:2] == ("knowledge", "projects"):
        return "project", _project_part(path)
    return "code", None


def _require_canonical_source(
    source_id: str,
    source_path: str,
    path: PurePosixPath,
    content: bytes,
    source_sha256: str,
) -> None:
    if not source_id or source_id != f"source:{source_path}" or not path.parts:
        raise ValueError("source identity is not canonical")
    if _sha256(content) != source_sha256:
        raise ValueError("source bytes do not match their canonical hash")


def _canonical_source_record(
    source_id: str,
    source_path: str,
    source_sha256: str,
    content: bytes,
    *,
    is_markdown: bool,
    metadata: SourceMetadata,
    candidate: _Candidate,
    searchable_start: int,
) -> SourceRecord:
    language = _classify_language(
        explicit=metadata.language,
        path=candidate.path,
        text=content[searchable_start:].decode("utf-8", errors="strict"),
    )
    return SourceRecord(
        source_id,
        source_path,
        source_sha256,
        len(content),
        "text/markdown" if is_markdown else "text/plain",
        language,
        None,
    )


def canonical_retrieval_chunks(
    *,
    source_id: str,
    source_path: str,
    source_sha256: str,
    content: bytes,
    extractor_version: str = EXTRACTOR_VERSION,
    deadline: float | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> tuple[RetrievalChunk, ...]:
    """Reconstruct every canonical chunk field from authoritative source bytes."""
    path = PurePosixPath(source_path)
    _require_canonical_source(source_id, source_path, path, content, source_sha256)
    kind, project = _source_kind(path)
    is_markdown, searchable_start, frontmatter = _markdown_head(
        source_path, content, deadline, cancelled
    )
    candidate = _Candidate(Path(*path.parts), source_path, kind, project, ())
    metadata = _metadata(frontmatter, candidate)
    source = _canonical_source_record(
        source_id,
        source_path,
        source_sha256,
        content,
        is_markdown=is_markdown,
        metadata=metadata,
        candidate=candidate,
        searchable_start=searchable_start,
    )
    return _chunks(
        source,
        metadata,
        content,
        searchable_start,
        heading_enabled=is_markdown,
        extractor_version=extractor_version,
        deadline=deadline,
        cancelled=cancelled,
    )


def _normalize_explicit_paths(
    values: Iterable[str | Path],
    normalize: Callable[[str | Path], str],
    *,
    label: str,
) -> tuple[str, ...]:
    normalized = []
    seen = set()
    for value in values:
        path = normalize(value)
        if path in seen:
            raise ValueError(f"duplicate {label}: {path}")
        seen.add(path)
        normalized.append(path)
    return tuple(sorted(normalized))


def _require_daily_files(normalized_daily: tuple[str, ...]) -> None:
    for path in normalized_daily:
        if not path.endswith(".md") or path == "knowledge/daily":
            raise ValueError("daily evidence must name an explicit Markdown file")


def _require_no_nested_root(root: str, others: tuple[str, ...]) -> None:
    for other in others:
        if other.startswith(root + "/"):
            raise ValueError(f"overlapping code roots are forbidden: {root}, {other}")


def _require_disjoint_roots(normalized_code: tuple[str, ...]) -> None:
    for index, root in enumerate(normalized_code):
        _require_no_nested_root(root, normalized_code[index + 1 :])


def _as_of_text(as_of: str | date | datetime | None) -> str | None:
    value = _metadata_value(as_of)
    if value is None:
        return None
    parsed = _as_datetime(value)
    assert parsed is not None
    return parsed.isoformat().replace("+00:00", "Z")


def _policy(
    *,
    daily_paths: Iterable[str | Path],
    code_roots: Iterable[str | Path],
    include_historical: bool,
    as_of: str | date | datetime | None,
    max_files: int,
    max_file_bytes: int,
    max_total_bytes: int,
    max_entries: int,
    max_directories: int,
    max_depth: int,
) -> SnapshotPolicy:
    if not isinstance(include_historical, bool):
        raise ValueError("include_historical must be boolean")
    normalized_daily = _normalize_explicit_paths(
        daily_paths,
        lambda path: _relative_posix(path, prefixes=("knowledge/daily",)),
        label="daily evidence path",
    )
    _require_daily_files(normalized_daily)
    normalized_code = _normalize_explicit_paths(
        code_roots, _code_root, label="code root"
    )
    _require_disjoint_roots(normalized_code)
    return SnapshotPolicy(
        daily_paths=normalized_daily,
        code_roots=normalized_code,
        include_historical=include_historical,
        as_of=_as_of_text(as_of),
        max_files=_positive_limit(max_files, "max_files"),
        max_file_bytes=_positive_limit(max_file_bytes, "max_file_bytes"),
        max_total_bytes=_positive_limit(max_total_bytes, "max_total_bytes"),
        max_entries=_positive_limit(max_entries, "max_entries"),
        max_directories=_positive_limit(max_directories, "max_directories"),
        max_depth=_positive_limit(max_depth, "max_depth", allow_zero=True),
    )


def _candidate_content(candidate: _Candidate, policy: SnapshotPolicy, label: str) -> bytes:
    if candidate.content is not None:
        return candidate.content
    _verify_seal(candidate.seal)
    content = read_stable_bytes(candidate.path, policy.max_file_bytes, label=label)
    _verify_seal(candidate.seal)
    return content


def _captured_record(
    candidate: _Candidate,
    content: bytes,
    metadata: SourceMetadata,
    is_markdown: bool,
    searchable_start: int,
    digest: str,
) -> SourceRecord:
    language = _classify_language(
        explicit=metadata.language,
        path=candidate.path,
        text=content[searchable_start:].decode("utf-8", errors="strict"),
    )
    return SourceRecord(
        logical_id=f"source:{candidate.relative}",
        relative_path=candidate.relative,
        sha256=digest,
        size=len(content),
        media_type="text/markdown" if is_markdown else "text/plain",
        language=language,
        git_oid=None,
    )


class _Capture:
    """Accumulates captured sources and their chunks under the policy limits."""

    def __init__(
        self,
        policy: SnapshotPolicy,
        deadline: float,
        cancelled: Callable[[], bool] | None,
    ) -> None:
        self.policy = policy
        self.deadline = deadline
        self.cancelled = cancelled
        self.captured: list[CapturedSource] = []
        self.chunks: list[RetrievalChunk] = []
        self.hashes: dict[str, str] = {}
        self.total = 0

    def add(self, candidate: _Candidate) -> None:
        content = _candidate_content(candidate, self.policy, "corpus source")
        self._count_bytes(len(content))
        is_markdown = candidate.path.suffix.casefold() == ".md"
        readable = is_markdown or _decodes_as_utf8(content)
        frontmatter, searchable_start = self._head(content, is_markdown)
        metadata = _metadata(frontmatter, candidate)
        digest = _sha256(content)
        self.hashes[candidate.relative] = digest
        if readable and _included(metadata, self.policy):
            self._store(candidate, content, metadata, is_markdown, searchable_start, digest)

    def _head(self, content: bytes, is_markdown: bool) -> tuple[dict[str, Any], int]:
        if not is_markdown:
            return {}, 0
        return _frontmatter(content, deadline=self.deadline, cancelled=self.cancelled)

    def _count_bytes(self, size: int) -> None:
        self.total += size
        if self.total > self.policy.max_total_bytes:
            raise ValueError("corpus total byte limit exceeded")

    def _store(
        self,
        candidate: _Candidate,
        content: bytes,
        metadata: SourceMetadata,
        is_markdown: bool,
        searchable_start: int,
        digest: str,
    ) -> None:
        record = _captured_record(
            candidate, content, metadata, is_markdown, searchable_start, digest
        )
        self.captured.append(CapturedSource(record, metadata, content))
        source_chunks = _chunks(
            record,
            metadata,
            content,
            searchable_start,
            heading_enabled=is_markdown,
            deadline=self.deadline,
            cancelled=self.cancelled,
        )
        if len(self.chunks) + len(source_chunks) > MAX_CORPUS_CHUNKS:
            raise ValueError("corpus chunk row ceiling exceeded")
        self.chunks.extend(source_chunks)


def _require_stable_membership(
    candidates: tuple[_Candidate, ...], current: tuple[_Candidate, ...]
) -> None:
    if tuple(item.relative for item in candidates) != tuple(
        item.relative for item in current
    ):
        raise CorpusChanged("corpus membership changed during collection")


def _require_stable_content(
    current: tuple[_Candidate, ...],
    policy: SnapshotPolicy,
    hashes: dict[str, str],
    deadline: float,
) -> None:
    for candidate in current:
        _check_deadline(deadline)
        content = _candidate_content(candidate, policy, "corpus validation source")
        if _sha256(content) != hashes[candidate.relative]:
            raise CorpusChanged(
                f"corpus source changed during collection: {candidate.relative}"
            )


def _capture(
    vault: Path,
    policy: SnapshotPolicy,
    deadline: float,
    cancelled: Callable[[], bool] | None,
) -> CorpusSnapshot:
    candidates = _discover(vault, policy, deadline)
    capture = _Capture(policy, deadline, cancelled)
    for candidate in candidates:
        _check_deadline(deadline)
        capture.add(candidate)
    _check_deadline(deadline)
    current = _discover(vault, policy, deadline)
    _require_stable_membership(candidates, current)
    _require_stable_content(current, policy, capture.hashes, deadline)
    corpus_hash = canonical_source_manifest_sha256(
        (source.record for source in capture.captured), policy
    )
    return CorpusSnapshot(
        tuple(capture.captured), tuple(capture.chunks), corpus_hash, policy
    )


def collect_corpus(
    vault: Path,
    *,
    daily_paths: Iterable[str | Path] = (),
    code_roots: Iterable[str | Path] = (),
    include_historical: bool = False,
    as_of: str | date | datetime | None = None,
    max_files: int = MAX_CORPUS_FILES,
    max_file_bytes: int = MAX_CORPUS_FILE_BYTES,
    max_total_bytes: int = MAX_CORPUS_TOTAL_BYTES,
    max_entries: int = MAX_CORPUS_INSPECTED_ENTRIES,
    max_directories: int = MAX_CORPUS_DIRECTORIES,
    max_depth: int = MAX_CORPUS_DEPTH,
    deadline: float | None = None,
    deadline_seconds: float | None = None,
    coordinator: object | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> CorpusSnapshot:
    """Capture one immutable corpus and reject any change before returning it."""
    root = Path(vault).resolve(strict=True)
    if not stat.S_ISDIR(_safe_info(root).st_mode):
        raise ValueError("vault must be a regular directory")
    selected_policy = _policy(
        daily_paths=daily_paths,
        code_roots=code_roots,
        include_historical=include_historical,
        as_of=as_of,
        max_files=max_files,
        max_file_bytes=max_file_bytes,
        max_total_bytes=max_total_bytes,
        max_entries=max_entries,
        max_directories=max_directories,
        max_depth=max_depth,
    )
    selected_deadline = _deadline_value(deadline, deadline_seconds)
    if coordinator is not None:
        _check_deadline(selected_deadline)
        remaining = max(0.0, selected_deadline - time.monotonic())
        gate = coordinator.writer_gate(wait_seconds=remaining)
    else:
        gate = contextlib.nullcontext()
    with gate:
        _check_processing_stop(selected_deadline, cancelled)
        return _capture(root, selected_policy, selected_deadline, cancelled)


@dataclass(frozen=True, slots=True)
class CorpusProbe:
    """Hash-free identity of the corpus selection: what is there, and how new.

    A probe answers two questions and no others: *has the selection changed at
    all* (membership plus per-file size and modification time) and *when was the
    corpus last written* (``newest_mtime_ns``). It never hashes and never
    decides staleness — that stays with :func:`collect_corpus`, which is this
    module's one definition of what a source is. It exists so a caller that
    wants to know whether paying for a snapshot is worth it can ask for far
    less than one.
    """

    entries: tuple[tuple[str, int, int], ...]
    newest_mtime_ns: int

    @property
    def file_count(self) -> int:
        return len(self.entries)


def _probe_entry(candidate: _Candidate) -> tuple[str, int, int] | None:
    """One (path, size, mtime) row, or nothing when the file just vanished."""
    try:
        info = _safe_info(candidate.path)
    except (OSError, PermissionError):
        return None
    return (candidate.relative, info.st_size, info.st_mtime_ns)


def _probe_rows(
    candidates: tuple[_Candidate, ...], deadline: float
) -> list[tuple[str, int, int]]:
    rows = []
    for candidate in candidates:
        _check_deadline(deadline)
        row = _probe_entry(candidate)
        if row is not None:
            rows.append(row)
    return rows


def probe_corpus_identity(
    vault: Path,
    *,
    daily_paths: Iterable[str | Path] = (),
    code_roots: Iterable[str | Path] = (),
    include_historical: bool = False,
    as_of: str | date | datetime | None = None,
    max_files: int = MAX_CORPUS_FILES,
    max_file_bytes: int = MAX_CORPUS_FILE_BYTES,
    max_total_bytes: int = MAX_CORPUS_TOTAL_BYTES,
    max_entries: int = MAX_CORPUS_INSPECTED_ENTRIES,
    max_directories: int = MAX_CORPUS_DIRECTORIES,
    max_depth: int = MAX_CORPUS_DEPTH,
    deadline: float | None = None,
    deadline_seconds: float | None = None,
) -> CorpusProbe:
    """Walk the corpus selection once and report identity without hashing.

    Measured on this vault (831 candidate files, 21 MB) on 2026-08-28: 0.078 s
    of CPU against 1.21 s for :func:`collect_corpus`, which additionally hashes,
    parses front matter, chunks, and reads every file a second time to prove the
    capture was coherent. The probe shares the selection walk with the collector
    deliberately, so there is never a second answer to "what is a source".
    """
    root = Path(vault).resolve(strict=True)
    selected_policy = _policy(
        daily_paths=daily_paths,
        code_roots=code_roots,
        include_historical=include_historical,
        as_of=as_of,
        max_files=max_files,
        max_file_bytes=max_file_bytes,
        max_total_bytes=max_total_bytes,
        max_entries=max_entries,
        max_directories=max_directories,
        max_depth=max_depth,
    )
    selected_deadline = _deadline_value(deadline, deadline_seconds)
    candidates = _discover(root, selected_policy, selected_deadline)
    rows = _probe_rows(candidates, selected_deadline)
    newest = max((row[2] for row in rows), default=0)
    return CorpusProbe(entries=tuple(sorted(rows)), newest_mtime_ns=newest)


def _override(value: object, fallback: object) -> object:
    if value is None:
        return fallback
    return value


def _snapshot_settings(
    policy: SnapshotPolicy, values: Mapping[str, object]
) -> dict[str, object]:
    defaults = {
        "daily_paths": policy.daily_paths,
        "code_roots": policy.code_roots,
        "include_historical": policy.include_historical,
        "as_of": policy.as_of,
        "max_files": policy.max_files,
        "max_file_bytes": policy.max_file_bytes,
        "max_total_bytes": policy.max_total_bytes,
        "max_entries": policy.max_entries,
        "max_directories": policy.max_directories,
        "max_depth": policy.max_depth,
    }
    return {key: _override(values.get(key), default) for key, default in defaults.items()}


def validate_live_snapshot(
    snapshot: CorpusSnapshot,
    vault: Path,
    *,
    daily_paths: Iterable[str | Path] | None = None,
    code_roots: Iterable[str | Path] | None = None,
    include_historical: bool | None = None,
    as_of: str | date | datetime | None = None,
    max_files: int | None = None,
    max_file_bytes: int | None = None,
    max_total_bytes: int | None = None,
    max_entries: int | None = None,
    max_directories: int | None = None,
    max_depth: int | None = None,
    deadline: float | None = None,
    deadline_seconds: float | None = None,
    coordinator: object | None = None,
    cancelled: Callable[[], bool] | None = None,
) -> None:
    """Rediscover and hash the live corpus immediately before publication."""
    if not isinstance(snapshot, CorpusSnapshot):
        raise TypeError("snapshot must be a CorpusSnapshot")
    settings = _snapshot_settings(
        snapshot.policy,
        {
            "daily_paths": daily_paths,
            "code_roots": code_roots,
            "include_historical": include_historical,
            "as_of": as_of,
            "max_files": max_files,
            "max_file_bytes": max_file_bytes,
            "max_total_bytes": max_total_bytes,
            "max_entries": max_entries,
            "max_directories": max_directories,
            "max_depth": max_depth,
        },
    )
    try:
        live = collect_corpus(
            vault,
            **settings,
            deadline=deadline,
            deadline_seconds=deadline_seconds,
            coordinator=coordinator,
            cancelled=cancelled,
        )
    except (FileNotFoundError, PermissionError) as exc:
        raise CorpusChanged("live corpus cannot reproduce captured membership") from exc
    if live.source_hashes != snapshot.source_hashes:
        raise CorpusChanged("live corpus membership or source hashes changed")
