"""Regenerate `knowledge/index.md` from `knowledge/notes/**/*.md`.

Supports both flat notes (current public layout) and typed subdirs
(concepts/decisions/patterns/debugging/qa) when present.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from memory_state import (  # noqa: E402
    ROOT,
    atomic_write,
    knowledge_publication_lock,
)
from vault_editorial import (  # noqa: E402
    ActiveNote,
    ActiveNoteSelection,
    parse_active_note_metadata,
    read_bounded_note,
    select_active_notes,
)

memory = ROOT / "knowledge"
knowledge = memory / "notes"
out = memory / "index.md"

TYPE_SECTIONS = {
    "concept": "Concepts",
    "decision": "Decisions",
    "pattern": "Patterns",
    "debugging": "Debugging",
    "qa": "Q&A",
    "entity": "Entities",
    "synthesis": "Syntheses",
    "comparison": "Comparisons",
    "connection": "Connections",
    "workflow": "Workflows",
    "raw-source": "Raw sources",
}

SUBDIR_SECTIONS = {
    "Concepts": knowledge / "concepts",
    "Decisions": knowledge / "decisions",
    "Patterns": knowledge / "patterns",
    "Debugging": knowledge / "debugging",
    "Q&A": knowledge / "qa",
}

SUMMARY_RE = re.compile(r"^One-sentence summary:\s*(.+?)\s*$", re.MULTILINE)
SKIP_NAMES = {"README.md", "index.md", "log.md"}


def _page_is_active(content: str) -> bool:
    return parse_active_note_metadata(content) is not None


def extract_hook(md_path: Path) -> str:
    try:
        text = read_bounded_note(md_path)
    except OSError:
        return ""
    return _extract_hook_from_content(text)


def _extract_hook_from_content(text: str) -> str:
    m = SUMMARY_RE.search(text)
    if m:
        return m.group(1).strip()
    lines = [ln.strip() for ln in text.splitlines()]
    for i, ln in enumerate(lines):
        if ln.startswith("# "):
            for follow in lines[i + 1 :]:
                if follow and not follow.startswith("#") and not follow.startswith("---"):
                    return follow
            break
    return ""


def extract_type(md_path: Path) -> str:
    try:
        text = read_bounded_note(md_path)
    except OSError:
        return ""
    metadata = parse_active_note_metadata(text)
    return metadata.page_type if metadata is not None else ""


def rel_link(md_path: Path) -> str:
    rel = md_path.relative_to(ROOT).with_suffix("")
    return rel.as_posix()


def _collect_note_buckets(
    selection: ActiveNoteSelection,
) -> dict[str, list[ActiveNote]]:
    buckets: dict[str, list[ActiveNote]] = {
        name: [] for name in TYPE_SECTIONS.values()
    }
    buckets["Other"] = []
    for note in selection.notes:
        section = TYPE_SECTIONS.get(note.page_type, "Other")
        buckets.setdefault(section, []).append(note)

    return buckets


def collect_pages() -> dict[str, list[Path]]:
    """Compatibility view over one immutable active-note selection."""
    # The shared selector excludes archived and superseded pages before bucketing.
    selection = select_active_notes(knowledge, root=ROOT)
    return {
        section: [note.path for note in notes]
        for section, notes in _collect_note_buckets(selection).items()
    }


def _render_index(selection: ActiveNoteSelection) -> str:
    lines = [
        "# Session Memory Index",
        "",
        (
            "<!-- llm-wiki-active-generation:"
            f"v{selection.generation.version}:"
            f"{selection.generation.canonical_sha256} -->"
        ),
        "",
        "This index catalogs durable memory distilled from AI agent sessions",
        "(OpenCode, Codex, Claude Code, Cursor, Antigravity).",
        "",
        "## Entry points",
        "- [[docs/operating-model]] — compile cadence, promotion rules, and the daily ↔ notes boundary.",
        "- Recent daily logs live under `knowledge/daily/` — raw, timestamped session captures awaiting compile.",
        "",
    ]

    buckets = _collect_note_buckets(selection)
    for name in list(TYPE_SECTIONS.values()) + ["Other"]:
        notes = sorted(
            buckets.get(name, []),
            key=lambda note: (note.path.name.casefold(), note.path.name),
        )
        if not notes:
            continue
        lines.append(f"## {name}")
        for note in notes:
            hook = _extract_hook_from_content(note.content)
            link = f"[[{rel_link(note.path)}]]"
            lines.append(f"- {link} — {hook}" if hook else f"- {link}")
        lines.append("")

    lines.extend(
        [
            "## Editorial note",
            "This index is vault metadata — a navigation map over `knowledge/notes/`, not a page derived from `raw/` or `inbox/`. It is regenerated by `scripts/rebuild_memory_index.py`; edits to page titles or one-sentence summaries will be picked up on the next rebuild.",
        ]
    )

    return "\n".join(lines).rstrip() + "\n"


def _rebuild_index_locked() -> bool:
    selection = select_active_notes(knowledge, root=ROOT)
    rendered = _render_index(selection)
    current = select_active_notes(knowledge, root=ROOT)
    if current.generation != selection.generation:
        return False
    atomic_write(out, rendered)
    return True


def rebuild_index() -> bool:
    """Publish one revalidated Markdown index under the shared writer lock."""
    with knowledge_publication_lock():
        return _rebuild_index_locked()


def main() -> int:
    return 0 if rebuild_index() else 1


if __name__ == "__main__":
    raise SystemExit(main())
