"""Regenerate `memory/index.md` from `memory/knowledge/*/*.md`.

Reads the vault root from `memory_state.ROOT` (honouring `$LLM_WIKI_ROOT`
or the sibling fallback) — previously this was hardcoded to
`$LLM_WIKI_ROOT`, breaking portability and breaking `compile_memory.py`
and `query_memory.py --file-back` on any machine where the vault lives
elsewhere.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from memory_state import ROOT  # noqa: E402

memory = ROOT / "memory"
knowledge = memory / "knowledge"
out = memory / "index.md"

sections = {
    "Concepts": knowledge / "concepts",
    "Decisions": knowledge / "decisions",
    "Patterns": knowledge / "patterns",
    "Debugging": knowledge / "debugging",
    "Q&A": knowledge / "qa",
}

SUMMARY_RE = re.compile(r"^One-sentence summary:\s*(.+?)\s*$", re.MULTILINE)


def extract_hook(md_path: Path) -> str:
    """Pull a one-line hook from a memory page.

    Prefers the `One-sentence summary:` convention; falls back to the first
    non-empty paragraph after the H1 title. Returns '' if nothing suitable.
    """
    text = md_path.read_text(encoding="utf-8")
    m = SUMMARY_RE.search(text)
    if m:
        return m.group(1).strip()
    lines = [ln.strip() for ln in text.splitlines()]
    for i, ln in enumerate(lines):
        if ln.startswith("# "):
            for follow in lines[i + 1 :]:
                if follow and not follow.startswith("#"):
                    return follow
            break
    return ""


def rel_link(md_path: Path) -> str:
    rel = md_path.relative_to(ROOT).with_suffix("")
    return rel.as_posix()


lines = [
    "# Session Memory Index",
    "",
    "This index catalogs durable memory distilled from Claude Code sessions.",
    "",
    "## Entry points",
    "- [[memory/operating-model]] — compile cadence, promotion rules, and the `memory/` ↔ `wiki/` boundary.",
    "- Recent daily logs live under `memory/daily/` — raw, timestamped session captures awaiting compile.",
    "",
]

for name, path in sections.items():
    lines.append(f"## {name}")
    pages = sorted(path.glob("*.md")) if path.exists() else []
    if pages:
        for p in pages:
            hook = extract_hook(p)
            link = f"[[{rel_link(p)}]]"
            lines.append(f"- {link} — {hook}" if hook else f"- {link}")
    else:
        lines.append("-")
    lines.append("")

lines.extend(
    [
        "## Editorial note",
        "This index is vault metadata — a navigation map over `memory/knowledge/`, not a page derived from `raw/` or `inbox/`. It is regenerated by `scripts/rebuild_memory_index.py`; edits to page titles or one-sentence summaries will be picked up on the next rebuild.",
    ]
)

out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
